# Generated by Django 4.0.4 on 2022-07-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0010_invoicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
